name: 'Apply Prequel Model Configs'
description: 'Greet someone and record the time'
inputs:
  use_dev_cli:  
    description: 'Use dev version of CLI. For internal Prequel use only'
    required: true
    default: false
  host:  
    description: "Host (scheme and port included) of Prequel instance. For US Cloud, use 'https://api.prequel.co/'"
    required: true
  api_key:  
    description: 'Prequel API Key'
    required: true
  mode:  
    description: "Can only be 'import' or 'export'"
    required: false
    default: 'export'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{ inputs.use_dev_cli }}